'use client';

import { useState } from 'react';
import Button from '@/components/ui/button';
import Badge from '@/components/ui/badge';
import type { ColumnMapping } from '@/lib/import/types';
import { IMPORT_TYPES, type ImportMode, type ImportType } from '@/lib/import/types';
import { importSchemas } from '@/lib/import/schema';

const typeLabels: Record<ImportType, string> = { usage_history: 'Usage History', business_event: 'Business Event', sales_order: 'Sales Order', item_substitute: 'Item Substitute' };
type ParseResponse = { batchId: string; headers: string[]; mapping: ColumnMapping; preview: Record<string, unknown>[]; status: 'SUCCESS' | 'WARNING' | 'ERROR'; issueCount: number; errorCount: number; warningCount: number };

export default function ImportWizard() {
  const [file, setFile] = useState<File | null>(null); const [type, setType] = useState<ImportType>('usage_history'); const [mode, setMode] = useState<ImportMode>('append'); const [result, setResult] = useState<ParseResponse | null>(null); const [mapping, setMapping] = useState<ColumnMapping>({}); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [imported, setImported] = useState(false);
  async function parse() { if (!file) return setMessage('CSV 또는 XLSX 파일을 선택하세요.'); setBusy(true); setMessage('서버에서 파일을 파싱하고 검증하는 중입니다.'); const form = new FormData(); form.append('file', file); form.append('importType', type); form.append('importMode', mode); const response = await fetch('/api/import/parse', { method: 'POST', body: form }); const body = await response.json(); setBusy(false); if (!response.ok) return setMessage(body.error ?? '파싱에 실패했습니다.'); setResult(body); setMapping(body.mapping); setImported(false); setMessage('Preview와 자동 매핑을 확인하세요.'); }
  async function validate() { if (!result) return; setBusy(true); const response = await fetch('/api/import/validate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ batchId: result.batchId, mapping }) }); const body = await response.json(); setBusy(false); if (!response.ok) return setMessage(body.error ?? '검증에 실패했습니다.'); setResult({ ...result, ...body }); setMessage(body.errorCount ? 'ERROR 행이 있어 Import할 수 없습니다.' : '검증 완료. 사용자 확인 후 Import할 수 있습니다.'); }
  async function commit() { if (!result || result.errorCount > 0) return; if (mode === 'replace' && !window.confirm('replace는 기존 파일 적재 데이터를 삭제할 수 있습니다. 계속하시겠습니까?')) return; setBusy(true); const response = await fetch(`/api/import/${result.batchId}/commit`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirmReplace: mode === 'replace' }) }); const body = await response.json(); setBusy(false); if (!response.ok) return setMessage(body.error ?? 'Import에 실패했습니다.'); setImported(true); setMessage(`Import 완료: ${body.inserted_rows ?? 0}행이 RAW에 저장되었습니다.`); }
  return <div className="stack"><div className="filter-bar panel"><input className="field" type="file" accept=".csv,.xlsx" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><select className="field" value={type} onChange={(event) => setType(event.target.value as ImportType)}>{IMPORT_TYPES.map((item) => <option key={item} value={item}>{typeLabels[item]}</option>)}</select><select className="field" value={mode} onChange={(event) => setMode(event.target.value as ImportMode)}><option value="append">append</option><option value="upsert">upsert</option><option value="replace">replace (ADMIN 확인)</option></select><Button variant="primary" type="button" onClick={parse} disabled={busy}>Parse & Validate</Button></div>{message && <p role="status">{message}</p>}{result && <><div className="kpi-grid"><div className="kpi-card"><div className="kpi-label">Batch</div><div className="kpi-value">{result.batchId.slice(0, 8)}</div></div><div className="kpi-card"><div className="kpi-label">Validation</div><div className="kpi-value"><Badge status={result.status === 'SUCCESS' ? 'SAFE' : result.status === 'WARNING' ? 'WARNING' : 'CRITICAL'}>{result.status}</Badge></div></div><div className="kpi-card"><div className="kpi-label">WARNING</div><div className="kpi-value">{result.warningCount}</div></div><div className="kpi-card"><div className="kpi-label">ERROR</div><div className="kpi-value">{result.errorCount}</div></div></div><div className="panel"><div className="panel-header"><div><h2>Column Mapping</h2><p>자동 추정값을 확인하거나 수정한 뒤 재검증하세요.</p></div></div><div className="panel-body stack">{importSchemas[type].map((field) => <label key={field.key}>{field.label}{field.required ? ' *' : ''}<select className="field" value={mapping[field.key] ?? ''} onChange={(event) => setMapping({ ...mapping, [field.key]: event.target.value })}><option value="">매핑 안 함</option>{result.headers.map((header) => <option key={header} value={header}>{header}</option>)}</select></label>)}<Button type="button" onClick={validate} disabled={busy}>Mapping 저장 및 재검증</Button></div></div><div className="panel"><div className="panel-header"><h2>Preview</h2><span>{result.preview.length}행 미리보기</span></div><div className="panel-body"><div className="data-table-wrap"><table className="data-table"><thead><tr>{result.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{result.preview.map((row, index) => <tr key={index}>{result.headers.map((header) => <td key={header}>{String(row[header] ?? '')}</td>)}</tr>)}</tbody></table></div></div></div><div className="button-row"><a className="button" href={`/api/import/${result.batchId}/errors`}>ERROR/WARNING CSV 다운로드</a><Button variant="primary" type="button" onClick={commit} disabled={busy || result.errorCount > 0 || imported}>사용자 확인 후 Import</Button></div></>}</div>;
}
