import PageHeader from '@/components/shell/page-header';
import Panel from '@/components/ui/panel';
import Badge from '@/components/ui/badge';
import { requireAdmin } from '@/lib/auth';
import ImportWizard from '@/components/import/import-wizard';
import { listImportHistory } from '@/lib/import/history';
import ImportHistoryActions from './import-history-actions';

type Batch = { batch_id: string; file_name: string; import_type: string; import_mode: string; total_rows: number; success_rows: number; warning_rows: number; error_rows: number; status: string; uploaded_by: string; uploaded_at: string; rollback_supported: boolean };
export default async function DataManagementPage() { await requireAdmin(); const { data: rows } = await listImportHistory(); const batches = (rows ?? []) as Batch[]; return <><PageHeader eyebrow="ADMIN / DATA MANAGEMENT" title="Data Management" description="파일을 staging에서 검증한 뒤 승인된 행만 RAW에 적재합니다." /><Panel title="File Upload" description="지원 타입: usage_history, business_event, sales_order, item_substitute"><ImportWizard /></Panel><Panel title="Import History" description="batch 단위 적재 이력과 rollback 상태"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>파일명</th><th>타입</th><th>모드</th><th>총 행</th><th>성공</th><th>경고</th><th>오류</th><th>사용자</th><th>시간</th><th>상태</th><th>관리</th></tr></thead><tbody>{batches.map((batch) => <tr key={batch.batch_id}><td>{batch.file_name}</td><td>{batch.import_type}</td><td>{batch.import_mode}</td><td className="numeric">{batch.total_rows}</td><td className="numeric">{batch.success_rows}</td><td className="numeric">{batch.warning_rows}</td><td className="numeric">{batch.error_rows}</td><td>{batch.uploaded_by.slice(0, 8)}</td><td>{new Date(batch.uploaded_at).toLocaleString('ko-KR')}</td><td><Badge status={batch.status === 'IMPORTED' ? 'SAFE' : batch.error_rows ? 'CRITICAL' : 'WARNING'}>{batch.status}</Badge></td><td><ImportHistoryActions batchId={batch.batch_id} rollbackSupported={batch.rollback_supported} /></td></tr>)}{!batches.length && <tr><td colSpan={11}>아직 Import History가 없습니다.</td></tr>}</tbody></table></div></Panel><Panel title="Validation Errors" description="ERROR와 WARNING 행을 원본 컬럼과 함께 다운로드합니다."><p>각 batch의 `ERROR/WARNING CSV 다운로드` 링크에서 오류 이력을 내려받을 수 있습니다.</p></Panel></>; }
