import PageHeader from '@/components/shell/page-header';
import Panel from '@/components/ui/panel';
import Badge from '@/components/ui/badge';
import EmptyValue from '@/components/ui/empty-value';
import { requireAdmin } from '@/lib/auth';
import ForecastRunActions from './forecast-run-actions';

type Run = { run_id: string; status: string; granularity: string | null; horizon: number | null; n_models: number; n_items: number; n_rows: number; data_snapshot_at: string | null; is_stale: boolean; triggered_email: string | null; started_at: string | null };
export default async function ForecastRunsPage() { const { supabase } = await requireAdmin(); const { data } = await supabase.schema('analytics').from('v_forecast_run').select('*').order('started_at', { ascending: false }).limit(100); const runs = (data ?? []) as Run[]; return <><PageHeader eyebrow="ADMIN / FORECAST RUNS" title="Forecast Runs" description="실행 이력, 모델 snapshot, 데이터 stale 상태를 확인합니다." actions={<ForecastRunActions />} /><Panel title="실행 이력"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>run_id</th><th>상태</th><th>실행시간</th><th>모델</th><th>SKU</th><th>결과 행</th><th>snapshot</th><th>stale</th><th>실행자</th><th>Backtest</th></tr></thead><tbody>{runs.map((run) => <tr key={run.run_id}><td>{run.run_id.slice(0, 8)}</td><td><Badge status={run.status === 'SUCCESS' ? 'SAFE' : run.status === 'FAILED' ? 'CRITICAL' : 'WARNING'}>{run.status}</Badge></td><td>{run.started_at ? new Date(run.started_at).toLocaleString('ko-KR') : <EmptyValue reasonCode="NOT_STARTED" />}</td><td className="numeric">{run.n_models}</td><td className="numeric">{run.n_items}</td><td className="numeric">{run.n_rows}</td><td>{run.data_snapshot_at ?? <EmptyValue reasonCode="NO_SNAPSHOT" />}</td><td><Badge status={run.is_stale ? 'WARNING' : 'SAFE'}>{run.is_stale ? 'STALE' : 'CURRENT'}</Badge></td><td>{run.triggered_email ?? <EmptyValue reasonCode="UNKNOWN_ACTOR" />}</td><td>{run.status === 'SUCCESS' ? <ForecastRunActions forecastRunId={run.run_id} /> : <EmptyValue reasonCode="FORECAST_NOT_SUCCESS" />}</td></tr>)}{!runs.length && <tr><td colSpan={10}><EmptyValue reasonCode="NO_FORECAST_RUN" /></td></tr>}</tbody></table></div></Panel></>; }
