'use client';

import { useMemo, useState } from 'react';
import Badge from '@/components/ui/badge';
import Button from '@/components/ui/button';
import EmptyValue from '@/components/ui/empty-value';
import ForecastOverlayChart, { type ForecastChartPoint } from '@/components/chart/forecast-overlay-chart';

type Row = { backtest_run_id: string; forecast_run_id: string; model_id: string; model_version: string; item_id: string; period: string; p50: number | null; p80: number | null; p90: number | null; actual: number | null; wape: number | null; mape: number | null; bias: number | null; rmse: number | null; mae: number | null; rank: number | null; calculation_status: string; reason_code: string | null; is_champion: boolean };
const metric = (value: number | null) => value == null ? null : value.toFixed(2);
export default function ModelComparisonTable({ rows, backtestRuns, isAdmin }: { rows: Row[]; backtestRuns: { backtest_run_id: string; forecast_run_id: string; test_start: string; test_end: string; status: string }[]; isAdmin: boolean }) {
  const [run, setRun] = useState(backtestRuns[0]?.backtest_run_id ?? 'ALL');
  const [sku, setSku] = useState(''); const [model, setModel] = useState('ALL'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState('');
  const runRows = useMemo(() => rows.filter((row) => (run === 'ALL' || row.backtest_run_id === run) && (!sku || row.item_id.toLowerCase().includes(sku.toLowerCase())) && (model === 'ALL' || row.model_id === model) && (!from || row.period >= from) && (!to || row.period <= to)), [from, model, rows, run, sku, to]);
  const modelIds = useMemo(() => Array.from(new Set(runRows.map((row) => row.model_id))).sort(), [runRows]);
  const activeModels = selected.length ? selected.filter((id) => modelIds.includes(id)) : modelIds;
  const chartData = useMemo(() => { const byPeriod = new Map<string, ForecastChartPoint>(); for (const row of runRows) { const point = byPeriod.get(row.period) ?? { period: row.period, actual: row.actual }; point.actual ??= row.actual; point[`${row.model_id}__p50`] = row.p50; point[`${row.model_id}__p80`] = row.p80; point[`${row.model_id}__p90`] = row.p90; byPeriod.set(row.period, point); } return Array.from(byPeriod.values()).sort((a, b) => a.period.localeCompare(b.period)); }, [runRows]);
  const performances = useMemo(() => Array.from(new Map(runRows.map((row) => [`${row.item_id}|${row.model_id}`, row])).values()), [runRows]);
  function exportCsv() { const headers = ['item_id', 'model_id', 'model_version', 'period', 'actual', 'p50', 'p80', 'p90', 'WAPE', 'MAPE', 'Bias', 'RMSE', 'MAE', 'rank', 'champion', 'reason_code']; const csv = [headers, ...runRows.map((row) => [row.item_id, row.model_id, row.model_version, row.period, row.actual, row.p50, row.p80, row.p90, row.wape, row.mape, row.bias, row.rmse, row.mae, row.rank, row.is_champion, row.reason_code])].map((line) => line.map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'model-comparison.csv'; link.click(); URL.revokeObjectURL(url); }
  async function manualChampion(itemId: string, modelId: string) { const reasonText = window.prompt('수동 Champion 지정 사유를 입력하세요.'); if (!reasonText?.trim() || run === 'ALL') return; const response = await fetch('/api/admin/champions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ backtestRunId: run, itemId, modelId, reasonText }) }); const body = await response.json(); setMessage(response.ok ? 'Manual Champion이 기록되었습니다.' : body.error ?? '변경 실패'); }
  return <><div className="filter-bar"><label>Backtest Run<select className="field" value={run} onChange={(event) => setRun(event.target.value)}><option value="ALL">전체</option>{backtestRuns.map((item) => <option key={item.backtest_run_id} value={item.backtest_run_id}>{item.backtest_run_id.slice(0, 8)} / {item.status}</option>)}</select></label><label>SKU<input className="field" value={sku} onChange={(event) => setSku(event.target.value)} placeholder="SKU 검색" /></label><label>Model<select className="field" value={model} onChange={(event) => setModel(event.target.value)}><option value="ALL">전체</option>{Array.from(new Set(rows.map((row) => row.model_id))).sort().map((id) => <option key={id}>{id}</option>)}</select></label><label>기간 시작<input className="field" type="month" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>기간 종료<input className="field" type="month" value={to} onChange={(event) => setTo(event.target.value)} /></label></div><div className="button-row"><Button type="button" onClick={exportCsv}>CSV Export</Button>{message && <span role="status">{message}</span>}</div><PanelTitle title="Model Toggle" /><div className="model-toggle">{modelIds.map((id) => <label key={id}><input type="checkbox" checked={activeModels.includes(id)} onChange={(event) => setSelected((items) => event.target.checked ? Array.from(new Set([...items, id])) : items.filter((item) => item !== id))} />{id}</label>)}</div><ForecastOverlayChart data={chartData} modelIds={activeModels} /><PanelTitle title="Model Performance" /><div className="data-table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Model Name</th><th>WAPE</th><th>MAPE</th><th>Bias</th><th>RMSE</th><th>MAE</th><th>Rank</th><th>Champion</th>{isAdmin && <th>관리</th>}</tr></thead><tbody>{performances.map((row) => <tr key={`${row.item_id}-${row.model_id}`}><td>{row.item_id}</td><td>{row.model_id}</td><td>{row.wape == null ? <EmptyValue reasonCode={row.reason_code ?? 'UNAVAILABLE'} /> : `${metric(row.wape)}%`}</td><td>{row.mape == null ? <EmptyValue reasonCode={row.reason_code ?? 'UNAVAILABLE'} /> : `${metric(row.mape)}%`}</td><td>{row.bias == null ? <EmptyValue reasonCode={row.reason_code ?? 'UNAVAILABLE'} /> : metric(row.bias)}</td><td>{row.rmse == null ? <EmptyValue reasonCode={row.reason_code ?? 'UNAVAILABLE'} /> : metric(row.rmse)}</td><td>{row.mae == null ? <EmptyValue reasonCode={row.reason_code ?? 'UNAVAILABLE'} /> : metric(row.mae)}</td><td>{row.rank ?? <EmptyValue reasonCode={row.reason_code ?? 'UNAVAILABLE'} />}</td><td><Badge status={row.is_champion ? 'SAFE' : 'WARNING'}>{row.is_champion ? 'CHAMPION' : 'CANDIDATE'}</Badge></td>{isAdmin && <td><Button type="button" onClick={() => manualChampion(row.item_id, row.model_id)}>수동 지정</Button></td>}</tr>)}{!performances.length && <tr><td colSpan={isAdmin ? 10 : 9}>조회 결과가 없습니다.</td></tr>}</tbody></table></div></>;
}
function PanelTitle({ title }: { title: string }) { return <div className="panel-header"><h2>{title}</h2></div>; }
