import PageHeader from '@/components/shell/page-header';
import Panel from '@/components/ui/panel';
import Badge from '@/components/ui/badge';
import EmptyValue from '@/components/ui/empty-value';
import { requireUser } from '@/lib/auth';

type Projection = { item_id: string; item_name: string | null; period: string; beginning_inventory: number | null; scheduled_receipts: number | null; confirmed_sales_order: number | null; soft_allocation: number | null; forecast_demand: number | null; ending_projected_inventory: number | null; effective_lead_time: number | null; reason_code: string | null; calculation_status: string };
const value = (amount: number | null, reason: string | null) => amount == null ? <EmptyValue reasonCode={reason ?? 'CALCULATION_UNAVAILABLE'} /> : amount.toFixed(1);
export default async function InventoryProjectionPage() { const { supabase } = await requireUser(); const { data } = await supabase.schema('analytics').from('v_inventory_projection').select('*').order('item_id').order('period'); const rows = (data ?? []) as Projection[]; return <><PageHeader eyebrow="ANALYSIS / INVENTORY PROJECTION" title="Inventory Projection" description="Champion Forecast와 공급·할당 데이터를 기간별로 결합한 Projection입니다." /><Panel title="Period Projection"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Period</th><th>Beginning</th><th>Receipt</th><th>Confirmed SO</th><th>Soft Allocation</th><th>Forecast</th><th>Ending</th><th>Effective LT</th><th>Risk</th><th>Reason</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.item_id}-${row.period}`}><td>{row.item_name ?? row.item_id}</td><td>{row.period}</td><td className="numeric">{value(row.beginning_inventory, row.reason_code)}</td><td className="numeric">{value(row.scheduled_receipts, row.reason_code)}</td><td className="numeric">{value(row.confirmed_sales_order, row.reason_code)}</td><td className="numeric">{value(row.soft_allocation, row.reason_code)}</td><td className="numeric">{value(row.forecast_demand, row.reason_code)}</td><td className="numeric">{value(row.ending_projected_inventory, row.reason_code)}</td><td className="numeric">{value(row.effective_lead_time, row.reason_code)}</td><td><Badge status={row.calculation_status === 'CALCULATED' ? 'SAFE' : 'CALCULATION_UNAVAILABLE'}>{row.calculation_status}</Badge></td><td>{row.reason_code ?? '—'}</td></tr>)}{!rows.length && <tr><td colSpan={11}><EmptyValue reasonCode="NO_PROJECTION_DATA" /></td></tr>}</tbody></table></div></Panel></>; }
