-- STEP 9: effective lead time and forecast-based inventory projection.
-- Missing inventory/lead time/forecast remains NULL with a reason code; no fake zero/default days.

create table if not exists raw.inventory_snapshot (
  snapshot_id bigint generated by default as identity primary key,
  item_id text not null,
  snapshot_date date not null,
  available_inventory numeric,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz default now(),
  source_record_id text
);
create table if not exists raw.purchase_order (
  purchase_order_id text primary key,
  item_id text not null,
  scheduled_receipt_date date,
  quantity numeric,
  status text,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz default now(),
  source_record_id text
);
create table if not exists raw.soft_allocation (
  allocation_id text primary key,
  item_id text not null,
  allocation_date date,
  quantity numeric,
  status text,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz default now(),
  source_record_id text
);
create table if not exists raw.lead_time_observation (
  observation_id bigint generated by default as identity primary key,
  item_id text not null,
  supplier_id text not null,
  order_date date,
  receipt_date date,
  lead_time_days numeric,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz default now(),
  source_record_id text
);

create index if not exists inventory_snapshot_item_date_idx on raw.inventory_snapshot(item_id, snapshot_date desc);
create index if not exists purchase_order_item_receipt_idx on raw.purchase_order(item_id, scheduled_receipt_date);
create index if not exists soft_allocation_item_date_idx on raw.soft_allocation(item_id, allocation_date);
create index if not exists lead_time_observation_item_idx on raw.lead_time_observation(item_id, supplier_id);
revoke all on raw.inventory_snapshot, raw.purchase_order, raw.soft_allocation, raw.lead_time_observation from anon, authenticated;
alter table raw.inventory_snapshot enable row level security;
alter table raw.purchase_order enable row level security;
alter table raw.soft_allocation enable row level security;
alter table raw.lead_time_observation enable row level security;

create table if not exists core.lead_time_policy (
  policy_id bigint generated by default as identity primary key,
  item_id text not null,
  supplier_id text not null,
  confirmed_lead_time_days numeric,
  effective_from date not null default current_date,
  effective_to date,
  active boolean not null default true,
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (item_id, supplier_id, effective_from)
);
create table if not exists core.lead_time_policy_history (
  history_id bigint generated by default as identity primary key,
  policy_id bigint,
  action text not null,
  before jsonb,
  after jsonb,
  changed_by uuid references auth.users(id),
  changed_at timestamptz not null default now()
);
create table if not exists core.inventory_projection_setting (
  setting_key text primary key default 'default',
  warning_lead_time_rule text not null default 'STOCKOUT_AFTER_RECEIPT',
  confirmed_order_statuses text[] not null default array['CONFIRMED','ALLOCATED'],
  soft_allocation_statuses text[] not null default array['ACTIVE','RESERVED'],
  soft_allocation_source_configured boolean not null default false,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);
insert into core.inventory_projection_setting(setting_key) values ('default') on conflict (setting_key) do nothing;

create or replace function core.record_lead_time_policy_history()
returns trigger language plpgsql security definer set search_path = core, public as $$
begin
  insert into core.lead_time_policy_history(policy_id, action, before, after, changed_by)
  values (coalesce(new.policy_id, old.policy_id), tg_op, case when tg_op = 'INSERT' then null else to_jsonb(old) end, case when tg_op = 'DELETE' then null else to_jsonb(new) end, coalesce(new.updated_by, auth.uid()));
  return coalesce(new, old);
end; $$;
drop trigger if exists lead_time_policy_history_trigger on core.lead_time_policy;
create trigger lead_time_policy_history_trigger after insert or update or delete on core.lead_time_policy for each row execute function core.record_lead_time_policy_history();
drop trigger if exists lead_time_policy_updated_at on core.lead_time_policy;
create trigger lead_time_policy_updated_at before update on core.lead_time_policy for each row execute function core.set_updated_at();

alter table core.lead_time_policy enable row level security;
alter table core.lead_time_policy_history enable row level security;
alter table core.inventory_projection_setting enable row level security;
grant select on core.lead_time_policy, core.lead_time_policy_history, core.inventory_projection_setting to authenticated;
grant insert, update, delete on core.lead_time_policy, core.inventory_projection_setting to authenticated;
drop policy if exists lead_time_policy_read on core.lead_time_policy;
drop policy if exists lead_time_policy_admin_write on core.lead_time_policy;
drop policy if exists lead_time_history_admin_read on core.lead_time_policy_history;
drop policy if exists inventory_projection_setting_read on core.inventory_projection_setting;
drop policy if exists inventory_projection_setting_admin_write on core.inventory_projection_setting;
create policy lead_time_policy_read on core.lead_time_policy for select to authenticated using (auth.role() = 'authenticated');
create policy lead_time_policy_admin_write on core.lead_time_policy for all to authenticated using (core.is_admin()) with check (core.is_admin());
create policy lead_time_history_admin_read on core.lead_time_policy_history for select to authenticated using (core.is_admin());
create policy inventory_projection_setting_read on core.inventory_projection_setting for select to authenticated using (auth.role() = 'authenticated');
create policy inventory_projection_setting_admin_write on core.inventory_projection_setting for all to authenticated using (core.is_admin()) with check (core.is_admin());

create or replace view analytics.v_lead_time_policy as
with actuals as (
  select item_id, supplier_id,
         percentile_cont(0.50) within group (order by lead_time_days) as p50,
         percentile_cont(0.80) within group (order by lead_time_days) as p80,
         percentile_cont(0.90) within group (order by lead_time_days) as p90,
         count(*)::integer as sample_count
  from raw.lead_time_observation
  where lead_time_days is not null and lead_time_days >= 0
  group by item_id, supplier_id
), current_policy as (
  select distinct on (item_id, supplier_id) *
  from core.lead_time_policy
  where active = true and effective_from <= current_date and (effective_to is null or effective_to >= current_date)
  order by item_id, supplier_id, effective_from desc, policy_id desc
)
select coalesce(a.item_id, p.item_id) as item_id,
       coalesce(ip.item_name, null) as item_name,
       coalesce(a.supplier_id, p.supplier_id) as supplier_id,
       a.sample_count, a.p50, a.p80, a.p90,
       p.confirmed_lead_time_days as admin_confirmed_lead_time,
       coalesce(p.confirmed_lead_time_days, a.p80) as effective_lead_time,
       p.effective_from, p.updated_by, p.policy_id,
       case when coalesce(p.confirmed_lead_time_days, a.p80) is null then 'NO_LEADTIME' when a.sample_count is null or a.sample_count < 2 then 'INSUFFICIENT_SAMPLE' end as reason_code
from actuals a
full join current_policy p on p.item_id = a.item_id and p.supplier_id = a.supplier_id
left join core.item_policy ip on ip.item_id = coalesce(a.item_id, p.item_id);

create or replace view analytics.v_inventory_projection as
with recursive setting as (
  select * from core.inventory_projection_setting where setting_key = 'default'
), current_inventory as (
  select distinct on (item_id) item_id, available_inventory, snapshot_date
  from raw.inventory_snapshot
  where snapshot_date <= current_date
  order by item_id, snapshot_date desc, snapshot_id desc
), current_champion as (
  select * from analytics.v_champion_model
), champion_forecast as (
  select c.item_id, c.champion_model_id as model_id, c.model_version, fr.period, fr.p50 as forecast_demand
  from current_champion c
  join core.backtest_run br on br.backtest_run_id = c.backtest_run_id
  join core.forecast_result fr on fr.run_id = br.forecast_run_id and fr.item_id = c.item_id and fr.model_id = c.champion_model_id and fr.model_version = c.model_version
  join core.forecast_run run on run.run_id = fr.run_id and run.status = 'SUCCESS'
), receipt_by_period as (
  select item_id, date_trunc('month', scheduled_receipt_date)::date as period, sum(quantity) as scheduled_receipts
  from raw.purchase_order
  where scheduled_receipt_date is not null and quantity is not null and quantity >= 0 and status not in ('CANCELLED','CLOSED')
  group by item_id, date_trunc('month', scheduled_receipt_date)::date
), order_by_period as (
  select so.item_id, date_trunc('month', coalesce(so.requested_date, so.order_date))::date as period, sum(so.quantity) as confirmed_sales_order
  from raw.sales_order so cross join setting st
  where so.quantity is not null and so.quantity >= 0 and so.status = any(st.confirmed_order_statuses)
  group by so.item_id, date_trunc('month', coalesce(so.requested_date, so.order_date))::date
), allocation_by_period as (
  select sa.item_id, date_trunc('month', sa.allocation_date)::date as period, sum(sa.quantity) as soft_allocation
  from raw.soft_allocation sa cross join setting st
  where sa.quantity is not null and sa.quantity >= 0 and sa.status = any(st.soft_allocation_statuses)
  group by sa.item_id, date_trunc('month', sa.allocation_date)::date
), base as (
  select f.*, coalesce(r.scheduled_receipts, 0) as scheduled_receipts,
         coalesce(o.confirmed_sales_order, 0) as confirmed_sales_order,
         coalesce(a.soft_allocation, 0) as soft_allocation,
         i.available_inventory, i.snapshot_date,
         lt.effective_lead_time,
         case when i.item_id is null then 'NO_INVENTORY_DATA' when lt.effective_lead_time is null then 'NO_LEADTIME' when f.forecast_demand is null then 'NO_FORECAST' when not st.soft_allocation_source_configured then 'SOFT_ALLOCATION_SOURCE_NOT_CONFIGURED' end as reason_code,
         row_number() over (partition by f.item_id order by f.period) as period_index
  from champion_forecast f
  left join receipt_by_period r on r.item_id = f.item_id and r.period = f.period
  left join order_by_period o on o.item_id = f.item_id and o.period = f.period
  left join allocation_by_period a on a.item_id = f.item_id and a.period = f.period
  left join current_inventory i on i.item_id = f.item_id
  left join (select item_id, max(effective_lead_time) as effective_lead_time from analytics.v_lead_time_policy group by item_id) lt on lt.item_id = f.item_id
  cross join setting st
), projected as (
  select b.item_id, b.model_id, b.model_version, b.period, b.period_index, b.available_inventory as beginning_inventory,
         b.scheduled_receipts, b.confirmed_sales_order, b.soft_allocation, b.forecast_demand,
         case when b.available_inventory is null or b.effective_lead_time is null or b.forecast_demand is null then null else b.available_inventory + b.scheduled_receipts - b.confirmed_sales_order - b.soft_allocation - b.forecast_demand end as ending_projected_inventory,
         b.effective_lead_time, b.snapshot_date, b.reason_code
  from base b where b.period_index = 1
  union all
  select b.item_id, b.model_id, b.model_version, b.period, b.period_index, p.ending_projected_inventory,
         b.scheduled_receipts, b.confirmed_sales_order, b.soft_allocation, b.forecast_demand,
         case when p.ending_projected_inventory is null or b.effective_lead_time is null or b.forecast_demand is null then null else p.ending_projected_inventory + b.scheduled_receipts - b.confirmed_sales_order - b.soft_allocation - b.forecast_demand end,
         b.effective_lead_time, b.snapshot_date, coalesce(p.reason_code, b.reason_code)
  from projected p join base b on b.item_id = p.item_id and b.period_index = p.period_index + 1
)
select p.item_id, ip.item_name, p.model_id as champion_model_id, p.model_version, p.period,
       p.beginning_inventory, p.scheduled_receipts, p.confirmed_sales_order, p.soft_allocation, p.forecast_demand, p.ending_projected_inventory,
       p.effective_lead_time, p.snapshot_date, p.reason_code,
       case when p.ending_projected_inventory is null then 'CALCULATION_UNAVAILABLE' else 'CALCULATED' end as calculation_status
from projected p left join core.item_policy ip on ip.item_id = p.item_id;

create or replace view analytics.v_stockout_risk as
with projection_summary as (
  select item_id, max(item_name) as item_name, max(champion_model_id) as champion_model_id, max(model_version) as model_version,
         min(period) filter (where ending_projected_inventory <= 0) as stockout_period,
         max(effective_lead_time) as effective_lead_time,
         case when count(*) filter (where reason_code = 'NO_INVENTORY_DATA') > 0 then 'NO_INVENTORY_DATA'
              when count(*) filter (where reason_code = 'NO_LEADTIME') > 0 then 'NO_LEADTIME'
              when count(*) filter (where reason_code = 'NO_FORECAST') > 0 then 'NO_FORECAST' end as reason_code,
         count(*) as horizon_periods,
         count(*) filter (where ending_projected_inventory is not null) as calculated_periods,
         max(period) as horizon_end
  from analytics.v_inventory_projection group by item_id
), all_items as (
  select item_id, max(item_name) as item_name from core.item_policy group by item_id
  union all
  select item_id, max(item_name) as item_name from analytics.v_sku_demand_profile group by item_id
), summary as (
  select * from projection_summary
  union all
  select i.item_id, i.item_name, null::text, null::text, null::date, null::numeric, 'NO_FORECAST', 0::bigint, 0::bigint, null::date
  from all_items i where not exists (select 1 from projection_summary p where p.item_id = i.item_id)
)
select s.item_id, s.item_name, s.champion_model_id, s.model_version, s.stockout_period,
       case when s.stockout_period is null then null else s.stockout_period end as stockout_date,
       case when s.calculated_periods = 0 then null when s.stockout_period is null then ((s.horizon_end + interval '1 month')::date - current_date)::numeric else (s.stockout_period - current_date)::numeric end as days_of_supply,
       case when s.calculated_periods = 0 then null when s.stockout_period is null then s.horizon_periods::numeric else greatest(0, extract(year from age(s.stockout_period, date_trunc('month', current_date))) * 12 + extract(month from age(s.stockout_period, date_trunc('month', current_date)))) end as months_of_supply,
       s.effective_lead_time,
       case when s.calculated_periods = 0 then 'CALCULATION_UNAVAILABLE' when s.reason_code in ('NO_INVENTORY_DATA','NO_LEADTIME','NO_FORECAST') then 'CALCULATION_UNAVAILABLE' when s.stockout_period is null then 'SAFE' when s.stockout_period > (current_date + ceil(s.effective_lead_time)::integer) then 'WARNING' else 'CRITICAL' end as risk_status,
       case when s.calculated_periods = 0 then coalesce(s.reason_code, 'NO_FORECAST') when s.reason_code in ('NO_INVENTORY_DATA','NO_LEADTIME','NO_FORECAST') then s.reason_code end as reason_code
from summary s;

create or replace view analytics.v_stockout_risk_kpi as
select count(*)::integer as total_items,
       count(*) filter (where risk_status = 'SAFE')::integer as n_safe,
       count(*) filter (where risk_status = 'WARNING')::integer as n_warning,
       count(*) filter (where risk_status = 'CRITICAL')::integer as n_critical,
       count(*) filter (where risk_status = 'CALCULATION_UNAVAILABLE')::integer as n_calculation_unavailable
from analytics.v_stockout_risk;

grant select on analytics.v_lead_time_policy, analytics.v_inventory_projection, analytics.v_stockout_risk, analytics.v_stockout_risk_kpi to authenticated;
