-- STEP 6: reproducible SQL baseline forecast engine.
-- Forecast calculations read core.v_train_demand only; no raw/test data is used.

alter table core.forecast_setting add column if not exists forecast_horizon integer not null default 3;
alter table core.forecast_setting drop constraint if exists forecast_setting_forecast_horizon_check;
alter table core.forecast_setting add constraint forecast_setting_forecast_horizon_check check (forecast_horizon > 0 and forecast_horizon <= 60);

create table if not exists core.model_config (
  model_id text primary key,
  model_name text not null,
  family text not null,
  engine text not null default 'SQL',
  version text not null,
  enabled boolean not null default true,
  is_default boolean not null default false,
  applicable_demand_type text[] not null default array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY']::text[],
  parameters jsonb not null default '{}'::jsonb,
  description text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

insert into core.model_config (model_id, model_name, family, engine, version, enabled, is_default, applicable_demand_type, parameters, description)
values
  ('MA_3M', 'Moving Average 3M', 'MOVING_AVERAGE', 'SQL', '1.0.0', true, true, array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'], '{"window": 3}'::jsonb, '최근 3개월 단순 이동평균'),
  ('MA_6M', 'Moving Average 6M', 'MOVING_AVERAGE', 'SQL', '1.0.0', true, false, array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'], '{"window": 6}'::jsonb, '최근 6개월 단순 이동평균'),
  ('WMA_3M', 'Weighted Moving Average 3M', 'WEIGHTED_MOVING_AVERAGE', 'SQL', '1.0.0', true, false, array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'], '{"window": 3, "weights": [3,2,1]}'::jsonb, '최근월부터 3:2:1 가중 이동평균'),
  ('PY_SAME_MONTH', 'Prior Year Same Month', 'SEASONAL_NAIVE', 'SQL', '1.0.0', true, false, array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'], '{"lag_months": 12}'::jsonb, '전년 동월 실제 학습값'),
  ('SEASONAL_NAIVE', 'Seasonal Naive', 'SEASONAL_NAIVE', 'SQL', '1.0.0', true, false, array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'], '{"season_months": 12}'::jsonb, '학습 구간에서 같은 월의 가장 최근 실제값')
on conflict (model_id) do nothing;

create table if not exists core.model_version (
  model_version_id bigint generated by default as identity primary key,
  run_id uuid not null references core.forecast_run(run_id) on delete cascade,
  model_id text not null,
  version text not null,
  parameters jsonb not null,
  definition jsonb not null,
  snapshotted_at timestamptz not null default now(),
  unique (run_id, model_id)
);

-- STEP 4 created a minimal forecast_run. Extend it without dropping prior results.
alter table core.forecast_run add column if not exists granularity text;
alter table core.forecast_run add column if not exists train_start date;
alter table core.forecast_run add column if not exists train_end date;
alter table core.forecast_run add column if not exists horizon integer;
alter table core.forecast_run add column if not exists champion_metric text;
alter table core.forecast_run add column if not exists models jsonb not null default '[]'::jsonb;
alter table core.forecast_run add column if not exists n_models integer not null default 0;
alter table core.forecast_run add column if not exists n_items integer not null default 0;
alter table core.forecast_run add column if not exists n_rows integer not null default 0;
alter table core.forecast_run add column if not exists started_at timestamptz;
alter table core.forecast_run add column if not exists finished_at timestamptz;
alter table core.forecast_run add column if not exists duration_ms bigint;
alter table core.forecast_run add column if not exists triggered_by uuid references auth.users(id);
alter table core.forecast_run add column if not exists triggered_email text;
alter table core.forecast_run add column if not exists note text;
alter table core.forecast_run add column if not exists message text;
alter table core.forecast_run add column if not exists is_stale boolean not null default false;

alter table core.forecast_run drop constraint if exists forecast_run_status_check;
update core.forecast_run set status = 'SUCCESS', is_stale = true where status = 'STALE';
update core.forecast_run set status = 'SUCCESS' where status = 'READY';
alter table core.forecast_run add constraint forecast_run_status_check check (status in ('RUNNING','SUCCESS','FAILED'));

create table if not exists core.forecast_result (
  run_id uuid not null references core.forecast_run(run_id) on delete restrict,
  model_id text not null,
  item_id text not null,
  period date not null,
  model_version text not null,
  predicted_qty numeric,
  p50 numeric,
  p80 numeric,
  p90 numeric,
  sigma numeric,
  basis text,
  calculation_reason text,
  created_at timestamptz not null default now(),
  primary key (run_id, model_id, item_id, period)
);

create index if not exists forecast_result_item_period_idx on core.forecast_result(item_id, period);
create index if not exists forecast_result_run_idx on core.forecast_result(run_id);

alter table core.model_config enable row level security;
alter table core.model_version enable row level security;
alter table core.forecast_run enable row level security;
alter table core.forecast_result enable row level security;
grant select on core.model_config, core.model_version, core.forecast_run, core.forecast_result to authenticated;
grant insert, update, delete on core.model_config to authenticated;

drop policy if exists model_config_authenticated_read on core.model_config;
drop policy if exists model_config_admin_write on core.model_config;
create policy model_config_authenticated_read on core.model_config for select to authenticated using (auth.role() = 'authenticated');
create policy model_config_admin_write on core.model_config for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists model_version_authenticated_read on core.model_version;
create policy model_version_authenticated_read on core.model_version for select to authenticated using (auth.role() = 'authenticated');
drop policy if exists forecast_run_authenticated_read on core.forecast_run;
create policy forecast_run_authenticated_read on core.forecast_run for select to authenticated using (auth.role() = 'authenticated');
drop policy if exists forecast_result_authenticated_read on core.forecast_result;
create policy forecast_result_authenticated_read on core.forecast_result for select to authenticated using (auth.role() = 'authenticated');

create or replace function core.run_baseline_forecast()
returns uuid language plpgsql security definer set search_path = core, analytics, public as $$
declare
  s record;
  run_key uuid := gen_random_uuid();
  snapshot_at timestamptz;
begin
  select setting_key, train_start, train_end, granularity, forecast_horizon
    into s
  from core.forecast_setting
  where setting_key = 'default' and active = true;
  if not found or s.train_start is null or s.train_end is null then raise exception 'FORECAST_SETTING_NOT_CONFIGURED'; end if;
  snapshot_at := coalesce((select max(loaded_at) from core.v_train_demand), now());

  insert into core.forecast_run(run_id, status, granularity, train_start, train_end, horizon, data_snapshot_at, started_at, triggered_by, triggered_email, message)
  values (run_key, 'RUNNING', s.granularity, s.train_start, s.train_end, s.forecast_horizon, snapshot_at, now(), auth.uid(), (select email from auth.users where id = auth.uid()), 'SQL baseline forecast started');

  begin
    insert into core.model_version(run_id, model_id, version, parameters, definition)
    select run_key, model_id, version, parameters,
           jsonb_build_object('model_name', model_name, 'family', family, 'engine', engine, 'applicable_demand_type', applicable_demand_type, 'description', description)
    from core.model_config where enabled = true;

    with enabled_models as (
      select * from core.model_config where enabled = true
    ), periods as (
      select gs::date as period_start, row_number() over(order by gs)::integer as period_index
      from generate_series(date_trunc('month', s.train_start)::date, date_trunc('month', s.train_end)::date, interval '1 month') gs
    ), items as (
      select item_id, demand_type from analytics.v_sku_demand_profile
    ), monthly as (
      select i.item_id, p.period_start, p.period_index,
             case when count(d.usage_date) = 0 then 0::numeric else sum(d.quantity) end as quantity
      from items i cross join periods p
      left join core.v_train_demand d on d.item_id = i.item_id and date_trunc('month', d.usage_date)::date = p.period_start
      group by i.item_id, p.period_start, p.period_index
    ), forecast_base as (
      select m.model_id, m.version, m.parameters, i.item_id, i.demand_type, f.period_start,
        case
          when m.model_id in ('MA_3M','MA_6M') then (select avg(x.quantity) from monthly x where x.item_id = i.item_id and x.period_start < f.period_start and x.period_start >= f.period_start - (((m.parameters->>'window')::integer) * interval '1 month') and x.quantity is not null having count(*) = (m.parameters->>'window')::integer)
          when m.model_id = 'WMA_3M' then (select sum(x.quantity * (m.parameters->'weights'->>(x.age - 1))::numeric) / sum((m.parameters->'weights'->>(x.age - 1))::numeric) from (select q.quantity, row_number() over(order by q.period_start desc)::integer as age from monthly q where q.item_id = i.item_id and q.period_start < f.period_start and q.quantity is not null) x where x.age <= (m.parameters->>'window')::integer having count(*) = (m.parameters->>'window')::integer)
          when m.model_id = 'PY_SAME_MONTH' then (select x.quantity from monthly x where x.item_id = i.item_id and x.period_start = f.period_start - (((m.parameters->>'lag_months')::integer) * interval '1 month'))
          when m.model_id = 'SEASONAL_NAIVE' then (select x.quantity from monthly x where x.item_id = i.item_id and x.period_start <= s.train_end and extract(month from x.period_start) = extract(month from f.period_start) and x.quantity is not null order by x.period_start desc limit 1)
        end as point_forecast
      from enabled_models m
      cross join items i
      cross join lateral (select gs::date as period_start from generate_series(s.train_end + interval '1 month', s.train_end + (s.forecast_horizon * interval '1 month'), interval '1 month') gs) f
      where m.applicable_demand_type is null or i.demand_type = any(m.applicable_demand_type)
    ), fitted as (
      select m.model_id, m.parameters, i.item_id, t.period_start, t.quantity,
        case
          when m.model_id in ('MA_3M','MA_6M') then (select avg(x.quantity) from monthly x where x.item_id = i.item_id and x.period_start < t.period_start and x.period_start >= t.period_start - (((m.parameters->>'window')::integer) * interval '1 month') and x.quantity is not null having count(*) = (m.parameters->>'window')::integer)
          when m.model_id = 'WMA_3M' then (select sum(x.quantity * (m.parameters->'weights'->>(x.age - 1))::numeric) / sum((m.parameters->'weights'->>(x.age - 1))::numeric) from (select q.quantity, row_number() over(order by q.period_start desc)::integer as age from monthly q where q.item_id = i.item_id and q.period_start < t.period_start and q.quantity is not null) x where x.age <= (m.parameters->>'window')::integer having count(*) = (m.parameters->>'window')::integer)
          when m.model_id = 'PY_SAME_MONTH' then (select x.quantity from monthly x where x.item_id = i.item_id and x.period_start = t.period_start - (((m.parameters->>'lag_months')::integer) * interval '1 month'))
          when m.model_id = 'SEASONAL_NAIVE' then (select x.quantity from monthly x where x.item_id = i.item_id and x.period_start < t.period_start and extract(month from x.period_start) = extract(month from t.period_start) and x.quantity is not null order by x.period_start desc limit 1)
        end as fitted_qty
      from enabled_models m cross join items i cross join monthly t
      where m.applicable_demand_type is null or i.demand_type = any(m.applicable_demand_type)
    ), sigmas as (
      select model_id, item_id, stddev_samp(quantity - fitted_qty) as sigma
      from fitted
      where fitted_qty is not null and quantity is not null
      group by model_id, item_id
    )
    insert into core.forecast_result(run_id, model_id, item_id, period, model_version, predicted_qty, p50, p80, p90, sigma, basis, calculation_reason)
    select run_key, b.model_id, b.item_id, b.period_start, b.version, b.point_forecast, b.point_forecast,
      case when b.point_forecast is not null and sg.sigma is not null then b.point_forecast + 0.8416212336 * sg.sigma end,
      case when b.point_forecast is not null and sg.sigma is not null then b.point_forecast + 1.2815515655 * sg.sigma end,
      sg.sigma,
      b.model_id,
      case when b.point_forecast is null then 'INSUFFICIENT_HISTORY' when sg.sigma is null then 'SIGMA_UNAVAILABLE' end
    from forecast_base b left join sigmas sg on sg.model_id = b.model_id and sg.item_id = b.item_id;

    update core.forecast_run r
       set status = 'SUCCESS', models = (select coalesce(jsonb_agg(model_id order by model_id), '[]'::jsonb) from core.model_version where run_id = run_key),
           n_models = (select count(*) from core.model_version where run_id = run_key),
           n_items = (select count(distinct item_id) from core.forecast_result where run_id = run_key),
           n_rows = (select count(*) from core.forecast_result where run_id = run_key),
           finished_at = now(), duration_ms = extract(epoch from (now() - started_at)) * 1000, message = 'SQL baseline forecast completed'
     where r.run_id = run_key;
  exception when others then
    update core.forecast_run set status = 'FAILED', finished_at = now(), duration_ms = extract(epoch from (now() - started_at)) * 1000, message = sqlerrm where run_id = run_key;
    raise;
  end;
  return run_key;
end; $$;

grant execute on function core.run_baseline_forecast() to authenticated;

create or replace function core.mark_forecast_runs_stale_after_import()
returns trigger language plpgsql security definer set search_path = core, public as $$
begin
  if new.status = 'IMPORTED' and old.status is distinct from new.status
     and new.import_type in ('usage_history', 'business_event', 'sales_order') then
    update core.forecast_run
       set is_stale = true, stale_since = coalesce(stale_since, new.imported_at),
           stale_reason = 'DEMAND_DATA_IMPORTED_AFTER_SNAPSHOT'
     where data_snapshot_at < coalesce(new.imported_at, now()) and is_stale = false;
  end if;
  return new;
end; $$;

drop trigger if exists mark_forecast_runs_stale on core.upload_batch;
create trigger mark_forecast_runs_stale after update of status on core.upload_batch for each row execute function core.mark_forecast_runs_stale_after_import();

create or replace view analytics.v_model_config as
select model_id, model_name, family, engine, version, enabled, is_default, applicable_demand_type, parameters, description, updated_at, updated_by
from core.model_config;

create or replace view analytics.v_forecast_run as
select run_id, status, granularity, train_start, train_end, horizon, champion_metric, data_snapshot_at, models, n_models, n_items, n_rows, started_at, finished_at, duration_ms, triggered_by, triggered_email, note, message, is_stale, stale_since, stale_reason
from core.forecast_run;

create or replace view analytics.v_forecast_result as
select run_id, model_id, item_id, period, model_version, predicted_qty, p50, p80, p90, sigma, basis, calculation_reason, created_at
from core.forecast_result;

create or replace view analytics.v_forecast_run_kpi as
select count(*)::integer as total_runs,
       count(*) filter (where status = 'SUCCESS')::integer as n_success,
       count(*) filter (where status = 'FAILED')::integer as n_failed,
       count(*) filter (where status = 'RUNNING')::integer as n_running,
       count(*) filter (where is_stale)::integer as n_stale
from core.forecast_run;

grant select on analytics.v_model_config, analytics.v_forecast_run, analytics.v_forecast_result, analytics.v_forecast_run_kpi to authenticated;
