create schema if not exists core;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  department text,
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

create or replace function core.set_updated_at() returns trigger
language plpgsql security invoker set search_path = core, public as $$
begin new.updated_at = now(); return new; end; $$;

create or replace function core.handle_new_user() returns trigger
language plpgsql security definer set search_path = core, public as $$
begin
  insert into core.app_user (user_id, email, name, department)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data->>'name', ''), new.raw_user_meta_data->>'department')
  on conflict (user_id) do update set email = excluded.email;
  return new;
end; $$;

create or replace function core.is_admin() returns boolean
language sql stable security definer set search_path = core, public as $$
  select exists (select 1 from core.app_user where user_id = auth.uid() and role = 'ADMIN' and active = true);
$$;

create or replace function core.audit_user_security_change() returns trigger
language plpgsql security definer set search_path = core, public as $$
begin
  if (old.role is distinct from new.role) or (old.active is distinct from new.active) then
    insert into core.audit_log (actor, action, target_type, target_id, before, after)
    values (auth.uid(), case when old.role is distinct from new.role then 'USER_ROLE_CHANGED' else 'USER_ACTIVE_CHANGED' end, 'app_user', new.user_id::text, to_jsonb(old), to_jsonb(new));
  end if;
  return new;
end; $$;

drop trigger if exists app_user_updated_at on core.app_user;
create trigger app_user_updated_at before update on core.app_user for each row execute function core.set_updated_at();
drop trigger if exists app_user_security_audit on core.app_user;
create trigger app_user_security_audit after update on core.app_user for each row execute function core.audit_user_security_change();
drop trigger if exists auth_user_created on auth.users;
create trigger auth_user_created after insert on auth.users for each row execute function core.handle_new_user();

revoke all on schema core from anon;
revoke all on all tables in schema core from anon;
grant usage on schema core to authenticated;
grant select on core.app_user to authenticated;
grant update (role, active, name, department, updated_at) on core.app_user to authenticated;
grant select on core.audit_log to authenticated;

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;
drop policy if exists app_user_self_read on core.app_user;
drop policy if exists app_user_admin_read on core.app_user;
drop policy if exists app_user_admin_update on core.app_user;
drop policy if exists audit_log_admin_read on core.audit_log;
create policy app_user_self_read on core.app_user for select to authenticated using (user_id = auth.uid() or core.is_admin());
create policy app_user_admin_update on core.app_user for update to authenticated using (core.is_admin()) with check (user_id <> auth.uid() or (role = 'ADMIN' and active = true));
create policy audit_log_admin_read on core.audit_log for select to authenticated using (core.is_admin());
