-- STEP 4: staged import pipeline. Additive migration; existing raw data is preserved.
create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(),
  file_name text not null,
  import_type text not null check (import_type in ('usage_history', 'business_event', 'sales_order', 'item_substitute')),
  import_mode text not null check (import_mode in ('append', 'upsert', 'replace')),
  total_rows integer not null default 0,
  success_rows integer not null default 0,
  warning_rows integer not null default 0,
  error_rows integer not null default 0,
  status text not null default 'STAGED' check (status in ('STAGED', 'VALIDATING', 'VALIDATED', 'READY', 'IMPORTED', 'VALIDATION_FAILED', 'ROLLED_BACK', 'FAILED')),
  uploaded_by uuid not null references auth.users(id),
  uploaded_at timestamptz not null default now(),
  imported_at timestamptz,
  mapping jsonb not null default '{}'::jsonb,
  rollback_supported boolean not null default true
);

create table if not exists core.import_staging (
  staging_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null,
  original_data jsonb not null,
  mapped_data jsonb not null default '{}'::jsonb,
  validation_status text not null default 'ERROR' check (validation_status in ('SUCCESS', 'WARNING', 'ERROR')),
  created_at timestamptz not null default now(),
  unique (batch_id, row_number)
);

create table if not exists core.column_mapping (
  mapping_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  import_type text not null check (import_type in ('usage_history', 'business_event', 'sales_order', 'item_substitute')),
  mapping_name text not null default 'default',
  mapping jsonb not null,
  updated_at timestamptz not null default now(),
  unique (user_id, import_type, mapping_name)
);

create table if not exists core.validation_error (
  validation_error_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null,
  field_name text not null,
  error_code text not null,
  error_message text not null,
  severity text not null check (severity in ('WARNING', 'ERROR')),
  original_value text,
  created_at timestamptz not null default now()
);

create index if not exists import_staging_batch_idx on core.import_staging(batch_id, row_number);
create index if not exists validation_error_batch_idx on core.validation_error(batch_id, row_number);

alter table core.upload_batch enable row level security;
alter table core.import_staging enable row level security;
alter table core.column_mapping enable row level security;
alter table core.validation_error enable row level security;
grant select, insert, update on core.upload_batch, core.import_staging, core.column_mapping, core.validation_error to authenticated;
grant usage, select on all sequences in schema core to authenticated;

drop policy if exists upload_batch_owner_read on core.upload_batch;
drop policy if exists upload_batch_owner_insert on core.upload_batch;
drop policy if exists upload_batch_admin_all on core.upload_batch;
drop policy if exists upload_batch_owner_update on core.upload_batch;
drop policy if exists staging_owner_access on core.import_staging;
drop policy if exists staging_admin_access on core.import_staging;
drop policy if exists mapping_owner_access on core.column_mapping;
drop policy if exists validation_owner_read on core.validation_error;
drop policy if exists validation_admin_read on core.validation_error;
create policy upload_batch_owner_read on core.upload_batch for select to authenticated using (uploaded_by = auth.uid() or core.is_admin());
create policy upload_batch_owner_insert on core.upload_batch for insert to authenticated with check (uploaded_by = auth.uid());
create policy upload_batch_admin_all on core.upload_batch for update to authenticated using (core.is_admin()) with check (core.is_admin());
create policy upload_batch_owner_update on core.upload_batch for update to authenticated using (uploaded_by = auth.uid() or core.is_admin()) with check (uploaded_by = auth.uid() or core.is_admin());
create policy staging_owner_access on core.import_staging for all to authenticated using (exists (select 1 from core.upload_batch b where b.batch_id = import_staging.batch_id and (b.uploaded_by = auth.uid() or core.is_admin()))) with check (exists (select 1 from core.upload_batch b where b.batch_id = import_staging.batch_id and (b.uploaded_by = auth.uid() or core.is_admin())));
create policy staging_admin_access on core.import_staging for delete to authenticated using (core.is_admin());
create policy mapping_owner_access on core.column_mapping for all to authenticated using (user_id = auth.uid() or core.is_admin()) with check (user_id = auth.uid() or core.is_admin());
create policy validation_owner_read on core.validation_error for select to authenticated using (exists (select 1 from core.upload_batch b where b.batch_id = validation_error.batch_id and b.uploaded_by = auth.uid()) or core.is_admin());
create policy validation_admin_read on core.validation_error for insert to authenticated with check (core.is_admin() or exists (select 1 from core.upload_batch b where b.batch_id = validation_error.batch_id and b.uploaded_by = auth.uid()));

create or replace function core.commit_import_batch(p_batch_id uuid, p_confirm_replace boolean default false)
returns jsonb language plpgsql security definer set search_path = core, raw, public as $$
declare b core.upload_batch%rowtype; inserted_count integer := 0;
begin
  select * into b from core.upload_batch where batch_id = p_batch_id and (uploaded_by = auth.uid() or core.is_admin()) for update;
  if not found then raise exception 'IMPORT_BATCH_NOT_FOUND_OR_FORBIDDEN'; end if;
  if b.status not in ('READY', 'VALIDATED') then raise exception 'IMPORT_BATCH_NOT_READY'; end if;
  if b.error_rows > 0 then raise exception 'IMPORT_HAS_VALIDATION_ERRORS'; end if;
  if b.import_mode = 'replace' and (not core.is_admin() or not p_confirm_replace) then raise exception 'REPLACE_REQUIRES_ADMIN_CONFIRMATION'; end if;
  if b.import_mode = 'replace' then
    update core.upload_batch set rollback_supported = false where batch_id = b.batch_id;
    if b.import_type = 'usage_history' then delete from raw.usage_history where batch_id in (select batch_id from core.upload_batch where import_type = b.import_type and status = 'IMPORTED'); end if;
    if b.import_type = 'business_event' then delete from raw.business_event where batch_id in (select batch_id from core.upload_batch where import_type = b.import_type and status = 'IMPORTED'); end if;
    if b.import_type = 'sales_order' then delete from raw.sales_order where batch_id in (select batch_id from core.upload_batch where import_type = b.import_type and status = 'IMPORTED'); end if;
    if b.import_type = 'item_substitute' then delete from raw.item_substitute where batch_id in (select batch_id from core.upload_batch where import_type = b.import_type and status = 'IMPORTED'); end if;
  end if;
  -- UPSERT replaces matching business keys from previous file batches, while APPEND keeps them.
  if b.import_mode = 'upsert' and b.import_type = 'usage_history' then
    delete from raw.usage_history r using core.import_staging s
    where s.batch_id = b.batch_id and s.validation_status in ('SUCCESS','WARNING')
      and r.source_type = 'FILE_UPLOAD' and r.item_id = s.mapped_data->>'item_id'
      and r.usage_date = (s.mapped_data->>'usage_date')::date;
  end if;
  if b.import_mode = 'upsert' and b.import_type = 'business_event' then
    delete from raw.business_event r using core.import_staging s
    where s.batch_id = b.batch_id and s.validation_status in ('SUCCESS','WARNING')
      and r.source_type = 'FILE_UPLOAD' and r.event_type = s.mapped_data->>'event_type'
      and r.event_date = (s.mapped_data->>'event_date')::date
      and coalesce(r.item_id, '') = coalesce(s.mapped_data->>'item_id', '');
  end if;
  if b.import_mode = 'upsert' and b.import_type = 'sales_order' then
    delete from raw.sales_order r using core.import_staging s
    where s.batch_id = b.batch_id and s.validation_status in ('SUCCESS','WARNING')
      and r.source_type = 'FILE_UPLOAD' and r.order_id = s.mapped_data->>'order_id'
      and r.item_id = s.mapped_data->>'item_id';
  end if;
  if b.import_mode = 'upsert' and b.import_type = 'item_substitute' then
    delete from raw.item_substitute r using core.import_staging s
    where s.batch_id = b.batch_id and s.validation_status in ('SUCCESS','WARNING')
      and r.source_type = 'FILE_UPLOAD' and r.item_id = s.mapped_data->>'item_id'
      and r.substitute_item_id = s.mapped_data->>'substitute_item_id';
  end if;
  if b.import_type = 'usage_history' then insert into raw.usage_history(item_id, usage_date, quantity, event_type, batch_id, source_type, loaded_at, source_record_id) select mapped_data->>'item_id', (mapped_data->>'usage_date')::date, nullif(mapped_data->>'quantity','')::numeric, mapped_data->>'event_type', b.batch_id, 'FILE_UPLOAD', now(), coalesce(mapped_data->>'source_record_id', row_number::text) from core.import_staging where batch_id = b.batch_id and validation_status in ('SUCCESS','WARNING'); end if;
  if b.import_type = 'business_event' then insert into raw.business_event(event_type, event_date, item_id, quantity, batch_id, source_type, loaded_at, source_record_id) select mapped_data->>'event_type', (mapped_data->>'event_date')::date, mapped_data->>'item_id', nullif(mapped_data->>'quantity','')::numeric, b.batch_id, 'FILE_UPLOAD', now(), coalesce(mapped_data->>'source_record_id', row_number::text) from core.import_staging where batch_id = b.batch_id and validation_status in ('SUCCESS','WARNING'); end if;
  if b.import_type = 'sales_order' then insert into raw.sales_order(order_id, order_date, customer_id, item_id, quantity, requested_date, status, batch_id, source_type, loaded_at, source_record_id) select mapped_data->>'order_id', (mapped_data->>'order_date')::date, mapped_data->>'customer_id', mapped_data->>'item_id', nullif(mapped_data->>'quantity','')::numeric, nullif(mapped_data->>'requested_date','')::date, mapped_data->>'status', b.batch_id, 'FILE_UPLOAD', now(), coalesce(mapped_data->>'source_record_id', row_number::text) from core.import_staging where batch_id = b.batch_id and validation_status in ('SUCCESS','WARNING'); end if;
  if b.import_type = 'item_substitute' then insert into raw.item_substitute(item_id, substitute_item_id, priority, active, batch_id, source_type, loaded_at, source_record_id) select mapped_data->>'item_id', mapped_data->>'substitute_item_id', nullif(mapped_data->>'priority','')::integer, case lower(trim(mapped_data->>'active')) when '' then true when 'true' then true when '1' then true when 'y' then true when 'n' then false when '0' then false when 'false' then false else true end, b.batch_id, 'FILE_UPLOAD', now(), coalesce(mapped_data->>'source_record_id', row_number::text) from core.import_staging where batch_id = b.batch_id and validation_status in ('SUCCESS','WARNING'); end if;
  select count(*) into inserted_count from core.import_staging where batch_id = b.batch_id and validation_status in ('SUCCESS','WARNING');
  update core.upload_batch set status = 'IMPORTED', success_rows = inserted_count, imported_at = now() where batch_id = b.batch_id;
  return jsonb_build_object('batch_id', b.batch_id, 'inserted_rows', inserted_count, 'rollback_supported', b.import_mode <> 'replace');
end; $$;

create or replace function core.rollback_import_batch(p_batch_id uuid)
returns jsonb language plpgsql security definer set search_path = core, raw, public as $$
declare b core.upload_batch%rowtype;
begin
  select * into b from core.upload_batch where batch_id = p_batch_id and (uploaded_by = auth.uid() or core.is_admin());
  if not found then raise exception 'IMPORT_BATCH_NOT_FOUND_OR_FORBIDDEN'; end if;
  if not b.rollback_supported or b.import_mode = 'replace' then raise exception 'REPLACE_ROLLBACK_NOT_SUPPORTED'; end if;
  if b.import_type = 'usage_history' then delete from raw.usage_history where batch_id = b.batch_id; end if;
  if b.import_type = 'business_event' then delete from raw.business_event where batch_id = b.batch_id; end if;
  if b.import_type = 'sales_order' then delete from raw.sales_order where batch_id = b.batch_id; end if;
  if b.import_type = 'item_substitute' then delete from raw.item_substitute where batch_id = b.batch_id; end if;
  update core.upload_batch set status = 'ROLLED_BACK' where batch_id = b.batch_id;
  return jsonb_build_object('batch_id', b.batch_id, 'status', 'ROLLED_BACK');
end; $$;

grant execute on function core.commit_import_batch(uuid, boolean), core.rollback_import_batch(uuid) to authenticated;

-- Forecast results are retained. Demand imports mark runs based on an older snapshot as STALE.
create table if not exists core.forecast_run (
  run_id uuid primary key default gen_random_uuid(),
  data_snapshot_at timestamptz not null,
  status text not null default 'READY' check (status in ('READY', 'STALE')),
  stale_reason text,
  stale_since timestamptz,
  created_at timestamptz not null default now()
);

alter table core.forecast_run enable row level security;
grant select on core.forecast_run to authenticated;
drop policy if exists forecast_run_authenticated_read on core.forecast_run;
create policy forecast_run_authenticated_read on core.forecast_run for select to authenticated using (auth.role() = 'authenticated');

create or replace function core.mark_forecast_runs_stale_after_import()
returns trigger language plpgsql security definer set search_path = core, public as $$
begin
  if new.status = 'IMPORTED' and old.status is distinct from new.status
     and new.import_type in ('usage_history', 'business_event', 'sales_order') then
    update core.forecast_run
       set status = 'STALE', stale_since = coalesce(stale_since, new.imported_at),
           stale_reason = 'DEMAND_DATA_IMPORTED_AFTER_SNAPSHOT'
     where data_snapshot_at < coalesce(new.imported_at, now()) and status <> 'STALE';
  end if;
  return new;
end; $$;

drop trigger if exists mark_forecast_runs_stale on core.upload_batch;
create trigger mark_forecast_runs_stale
after update of status on core.upload_batch
for each row execute function core.mark_forecast_runs_stale_after_import();
