-- STEP 3: raw ingestion model, policy configuration, and train/test isolation.
-- This migration is additive. It does not drop or recreate existing business tables.

create schema if not exists raw;
create schema if not exists analytics;

-- Common ingestion metadata is nullable so existing imported rows remain valid.
create table if not exists raw.usage_history (
  id bigint generated by default as identity primary key,
  item_id text not null,
  usage_date date not null,
  quantity numeric,
  event_type text,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz default now(),
  source_record_id text
);
alter table raw.usage_history add column if not exists batch_id uuid;
alter table raw.usage_history add column if not exists source_type text;
alter table raw.usage_history add column if not exists loaded_at timestamptz;
alter table raw.usage_history add column if not exists source_record_id text;
alter table raw.usage_history add column if not exists event_type text;
alter table raw.usage_history alter column batch_id drop not null;
alter table raw.usage_history alter column source_type drop not null;
alter table raw.usage_history alter column loaded_at drop not null;
alter table raw.usage_history alter column source_record_id drop not null;

create table if not exists raw.business_event (
  id bigint generated by default as identity primary key,
  event_type text not null,
  event_date date not null,
  item_id text,
  quantity numeric,
  attributes jsonb not null default '{}'::jsonb,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz default now(),
  source_record_id text
);

create table if not exists raw.sales_order (
  id bigint generated by default as identity primary key,
  order_id text not null,
  order_date date,
  customer_id text,
  item_id text,
  quantity numeric,
  requested_date date,
  status text,
  attributes jsonb not null default '{}'::jsonb,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz default now(),
  source_record_id text
);

create table if not exists raw.item_substitute (
  id bigint generated by default as identity primary key,
  item_id text not null,
  substitute_item_id text not null,
  priority integer,
  active boolean not null default true,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz default now(),
  source_record_id text
);

create index if not exists usage_history_item_date_idx on raw.usage_history (item_id, usage_date);
create index if not exists business_event_date_idx on raw.business_event (event_date);
create index if not exists sales_order_date_idx on raw.sales_order (order_date);
create index if not exists item_substitute_item_idx on raw.item_substitute (item_id, active);

create table if not exists core.policy_config (
  policy_key text primary key,
  service_level numeric,
  review_period_days integer,
  safety_buffer_days integer,
  config jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.outlier_rule (
  rule_id bigint generated by default as identity primary key,
  rule_code text not null unique,
  rule_type text not null check (rule_type in ('PROJECT_DEMAND', 'RETURN', 'DUPLICATE', 'OTHER')),
  description text,
  exclude_from_training boolean not null default true,
  criteria jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.item_policy (
  item_id text primary key,
  moq numeric,
  pack_size numeric,
  item_grade text,
  service_level numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.forecast_setting (
  setting_key text primary key default 'default',
  train_start date,
  train_end date,
  test_start date,
  test_end date,
  granularity text not null default 'MONTH',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forecast_setting_date_order check (
    train_start is null or train_end is null or train_start <= train_end
  ),
  constraint forecast_setting_test_order check (
    test_start is null or test_end is null or test_start <= test_end
  ),
  constraint forecast_setting_non_overlap check (
    train_end is null or test_start is null or train_end < test_start
  )
);

insert into core.forecast_setting (setting_key)
values ('default')
on conflict (setting_key) do nothing;

drop trigger if exists policy_config_updated_at on core.policy_config;
create trigger policy_config_updated_at before update on core.policy_config for each row execute function core.set_updated_at();
drop trigger if exists outlier_rule_updated_at on core.outlier_rule;
create trigger outlier_rule_updated_at before update on core.outlier_rule for each row execute function core.set_updated_at();
drop trigger if exists item_policy_updated_at on core.item_policy;
create trigger item_policy_updated_at before update on core.item_policy for each row execute function core.set_updated_at();
drop trigger if exists forecast_setting_updated_at on core.forecast_setting;
create trigger forecast_setting_updated_at before update on core.forecast_setting for each row execute function core.set_updated_at();

-- Raw tables are ingestion-owned. No anon/authenticated policy means direct reads and writes are denied.
alter table raw.usage_history enable row level security;
alter table raw.business_event enable row level security;
alter table raw.sales_order enable row level security;
alter table raw.item_substitute enable row level security;
revoke all on all tables in schema raw from anon, authenticated;

alter table core.policy_config enable row level security;
alter table core.outlier_rule enable row level security;
alter table core.item_policy enable row level security;
alter table core.forecast_setting enable row level security;
grant select on core.policy_config, core.outlier_rule, core.item_policy, core.forecast_setting to authenticated;
grant insert, update, delete on core.policy_config, core.outlier_rule, core.item_policy, core.forecast_setting to authenticated;

drop policy if exists policy_config_authenticated_read on core.policy_config;
drop policy if exists policy_config_admin_write on core.policy_config;
drop policy if exists outlier_rule_authenticated_read on core.outlier_rule;
drop policy if exists outlier_rule_admin_write on core.outlier_rule;
drop policy if exists item_policy_authenticated_read on core.item_policy;
drop policy if exists item_policy_admin_write on core.item_policy;
drop policy if exists forecast_setting_authenticated_read on core.forecast_setting;
drop policy if exists forecast_setting_admin_write on core.forecast_setting;

create policy policy_config_authenticated_read on core.policy_config for select to authenticated using (auth.role() = 'authenticated');
create policy policy_config_admin_write on core.policy_config for all to authenticated using (core.is_admin()) with check (core.is_admin());
create policy outlier_rule_authenticated_read on core.outlier_rule for select to authenticated using (auth.role() = 'authenticated');
create policy outlier_rule_admin_write on core.outlier_rule for all to authenticated using (core.is_admin()) with check (core.is_admin());
create policy item_policy_authenticated_read on core.item_policy for select to authenticated using (auth.role() = 'authenticated');
create policy item_policy_admin_write on core.item_policy for all to authenticated using (core.is_admin()) with check (core.is_admin());
create policy forecast_setting_authenticated_read on core.forecast_setting for select to authenticated using (auth.role() = 'authenticated');
create policy forecast_setting_admin_write on core.forecast_setting for all to authenticated using (core.is_admin()) with check (core.is_admin());

-- These are the only application-facing paths for forecast training and test scoring.
create or replace view core.v_train_demand as
select
  uh.item_id,
  uh.usage_date,
  uh.quantity,
  uh.batch_id,
  uh.source_type,
  uh.loaded_at,
  uh.source_record_id,
  fs.setting_key
from raw.usage_history uh
join core.forecast_setting fs on fs.setting_key = 'default' and fs.active = true
where fs.train_start is not null
  and fs.train_end is not null
  and uh.usage_date between fs.train_start and fs.train_end
  and not exists (
    select 1
    from core.outlier_rule orule
    where orule.active = true
      and orule.exclude_from_training = true
      and orule.rule_code = uh.event_type
  );

create or replace view core.v_test_actual as
select
  uh.item_id,
  uh.usage_date,
  uh.quantity,
  uh.batch_id,
  uh.source_type,
  uh.loaded_at,
  uh.source_record_id,
  fs.setting_key
from raw.usage_history uh
join core.forecast_setting fs on fs.setting_key = 'default' and fs.active = true
where fs.test_start is not null
  and fs.test_end is not null
  and uh.usage_date between fs.test_start and fs.test_end;

create or replace view analytics.v_data_coverage as
with data_window as (
  select min(usage_date) as data_start, max(usage_date) as data_end
  from raw.usage_history
), setting as (
  select train_start, train_end, test_start, test_end, granularity
  from core.forecast_setting
  where setting_key = 'default' and active = true
)
select
  data_window.data_start,
  data_window.data_end,
  setting.train_start,
  setting.train_end,
  setting.test_start,
  setting.test_end,
  (select count(*) from core.v_train_demand) as train_row_count,
  (select count(*) from core.v_test_actual) as test_row_count,
  setting.granularity,
  (setting.train_start is not null and setting.train_end is not null and data_window.data_start <= setting.train_start and data_window.data_end >= setting.train_end) as train_window_ok,
  (setting.test_start is not null and setting.test_end is not null and data_window.data_start <= setting.test_start and data_window.data_end >= setting.test_end) as test_window_ok
from data_window cross join setting;

grant select on core.v_train_demand, core.v_test_actual to authenticated;
grant select on analytics.v_data_coverage to authenticated;

-- Verification queries (run after applying this migration):
-- select * from analytics.v_data_coverage;
-- select count(*) from core.v_train_demand train join core.v_test_actual test using (item_id, usage_date);
-- select count(*) from core.v_test_actual where usage_date not between (select test_start from core.forecast_setting where setting_key = 'default') and (select test_end from core.forecast_setting where setting_key = 'default');
