-- STEP 11: 운영형 Agent 대화 저장
-- 질문과 답변은 core.save_agent_turn 하나의 PostgreSQL transaction으로 저장한다.

create table if not exists core.agent_conversation (
  conversation_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  user_email text not null,
  title text not null,
  started_at timestamptz not null default now(),
  last_at timestamptz not null default now()
);

create table if not exists core.agent_message (
  message_id bigint generated by default as identity primary key,
  conversation_id uuid not null references core.agent_conversation(conversation_id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'tool', 'system')),
  content text not null,
  answer jsonb,
  tool_trace jsonb,
  usage jsonb,
  guardrail jsonb,
  created_at timestamptz not null default now()
);

create index if not exists agent_conversation_user_last_idx
  on core.agent_conversation(user_id, last_at desc);
create index if not exists agent_message_conversation_created_idx
  on core.agent_message(conversation_id, created_at);

revoke all on core.agent_conversation, core.agent_message from anon, authenticated;
grant usage on schema core to authenticated;
grant select, insert on core.agent_conversation, core.agent_message to authenticated;
grant usage, select on all sequences in schema core to authenticated;

alter table core.agent_conversation enable row level security;
alter table core.agent_message enable row level security;

drop policy if exists agent_conversation_owner_select on core.agent_conversation;
create policy agent_conversation_owner_select on core.agent_conversation
  for select to authenticated
  using (user_id = auth.uid() or core.is_admin());

drop policy if exists agent_conversation_owner_insert on core.agent_conversation;
create policy agent_conversation_owner_insert on core.agent_conversation
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists agent_message_owner_select on core.agent_message;
create policy agent_message_owner_select on core.agent_message
  for select to authenticated
  using (exists (
    select 1 from core.agent_conversation c
    where c.conversation_id = agent_message.conversation_id
      and (c.user_id = auth.uid() or core.is_admin())
  ));

drop policy if exists agent_message_owner_insert on core.agent_message;
create policy agent_message_owner_insert on core.agent_message
  for insert to authenticated
  with check (exists (
    select 1 from core.agent_conversation c
    where c.conversation_id = agent_message.conversation_id
      and c.user_id = auth.uid()
  ));

create or replace function core.save_agent_turn(
  p_conversation_id uuid,
  p_title text,
  p_question text,
  p_answer jsonb,
  p_tool_trace jsonb default null,
  p_usage jsonb default null,
  p_guardrail jsonb default null
) returns uuid
language plpgsql
security definer
set search_path = core, public
as $$
declare
  v_conversation_id uuid := p_conversation_id;
begin
  if auth.uid() is null then raise exception 'UNAUTHENTICATED'; end if;
  if nullif(trim(p_question), '') is null then raise exception 'QUESTION_REQUIRED'; end if;

  if v_conversation_id is null then
    insert into core.agent_conversation (user_id, user_email, title)
    values (
      auth.uid(),
      coalesce((select email from auth.users where id = auth.uid()), ''),
      coalesce(nullif(trim(p_title), ''), left(trim(p_question), 80))
    )
    returning conversation_id into v_conversation_id;
  else
    if not exists (
      select 1 from core.agent_conversation
      where conversation_id = v_conversation_id and user_id = auth.uid()
    ) then raise exception 'CONVERSATION_FORBIDDEN'; end if;
    update core.agent_conversation
    set title = coalesce(nullif(trim(p_title), ''), title), last_at = now()
    where conversation_id = v_conversation_id;
  end if;

  insert into core.agent_message (conversation_id, role, content)
  values (v_conversation_id, 'user', trim(p_question));
  insert into core.agent_message (conversation_id, role, content, answer, tool_trace, usage, guardrail)
  values (v_conversation_id, 'assistant', coalesce(p_answer->>'answer', ''), p_answer, p_tool_trace, p_usage, p_guardrail);
  return v_conversation_id;
end;
$$;

revoke all on function core.save_agent_turn(uuid, text, text, jsonb, jsonb, jsonb, jsonb) from public;
grant execute on function core.save_agent_turn(uuid, text, text, jsonb, jsonb, jsonb, jsonb) to authenticated;

comment on function core.save_agent_turn(uuid, text, text, jsonb, jsonb, jsonb, jsonb)
  is 'Atomically inserts one user question and its Agent answer; ownership is checked with auth.uid().';
