-- STEP 7: Backtest scoring, champion selection, and model comparison.
-- Scoring reads core.forecast_result + core.v_test_actual only.

alter table core.forecast_setting add column if not exists champion_metric text not null default 'WAPE';
alter table core.forecast_setting add column if not exists reference_model_id text not null default 'MA_3M';
alter table core.forecast_setting add column if not exists tie_break_rule text not null default 'ABS_BIAS,RMSE,MAE,MODEL_ID';
alter table core.forecast_setting drop constraint if exists forecast_setting_champion_metric_check;
alter table core.forecast_setting add constraint forecast_setting_champion_metric_check check (champion_metric in ('WAPE','MAPE','RMSE','MAE'));

create table if not exists core.backtest_run (
  backtest_run_id uuid primary key default gen_random_uuid(),
  forecast_run_id uuid not null references core.forecast_run(run_id) on delete restrict,
  test_start date not null,
  test_end date not null,
  metric text not null default 'WAPE',
  status text not null default 'RUNNING' check (status in ('RUNNING','SUCCESS','FAILED')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  triggered_by uuid references auth.users(id),
  message text
);

create table if not exists core.model_performance (
  performance_id bigint generated by default as identity primary key,
  run_id uuid not null references core.forecast_run(run_id) on delete restrict,
  backtest_run_id uuid not null references core.backtest_run(backtest_run_id) on delete cascade,
  forecast_run_id uuid not null references core.forecast_run(run_id) on delete restrict,
  model_id text not null,
  model_version text not null,
  item_id text not null,
  n_periods integer not null default 0,
  wape numeric,
  mape numeric,
  bias numeric,
  rmse numeric,
  mae numeric,
  baseline_improvement numeric,
  rank integer,
  calculation_status text not null default 'SUCCESS',
  reason_code text,
  calculated_at timestamptz not null default now(),
  unique (backtest_run_id, model_id, item_id)
);

comment on table core.model_performance is 'WAPE=100*sum(abs(F-A))/sum(abs(A)); MAPE=100*mean(abs(F-A)/abs(A)) over A<>0; Bias=mean(F-A), positive means over-forecast; RMSE and MAE use periods with both F and A. Missing/zero denominators remain null with reason_code.';

create table if not exists core.champion_model (
  champion_id bigint generated by default as identity primary key,
  backtest_run_id uuid not null references core.backtest_run(backtest_run_id) on delete restrict,
  item_id text not null,
  champion_model_id text not null,
  model_version text not null,
  champion_metric text not null,
  champion_metric_value numeric,
  wape numeric,
  mape numeric,
  bias numeric,
  rmse numeric,
  candidate_performance jsonb not null default '[]'::jsonb,
  selection_reason text not null,
  selection_method text not null check (selection_method in ('AUTO','MANUAL')),
  selected_at timestamptz not null default now(),
  selected_by uuid references auth.users(id)
);

create table if not exists core.champion_selection_issue (
  issue_id bigint generated by default as identity primary key,
  backtest_run_id uuid not null references core.backtest_run(backtest_run_id) on delete cascade,
  item_id text not null,
  reason_code text not null,
  created_at timestamptz not null default now(),
  unique (backtest_run_id, item_id)
);

create index if not exists model_performance_item_idx on core.model_performance(item_id, backtest_run_id);
create index if not exists champion_model_item_idx on core.champion_model(item_id, selected_at desc);

alter table core.backtest_run enable row level security;
alter table core.model_performance enable row level security;
alter table core.champion_model enable row level security;
alter table core.champion_selection_issue enable row level security;
grant select on core.backtest_run, core.model_performance, core.champion_model, core.champion_selection_issue to authenticated;

drop policy if exists backtest_run_read on core.backtest_run;
drop policy if exists model_performance_read on core.model_performance;
drop policy if exists champion_model_read on core.champion_model;
drop policy if exists champion_issue_read on core.champion_selection_issue;
create policy backtest_run_read on core.backtest_run for select to authenticated using (auth.role() = 'authenticated');
create policy model_performance_read on core.model_performance for select to authenticated using (auth.role() = 'authenticated');
create policy champion_model_read on core.champion_model for select to authenticated using (auth.role() = 'authenticated');
create policy champion_issue_read on core.champion_selection_issue for select to authenticated using (auth.role() = 'authenticated');

create or replace function core.run_backtest(p_forecast_run_id uuid)
returns uuid language plpgsql security definer set search_path = core, public as $$
declare
  setting record;
  backtest_key uuid := gen_random_uuid();
  reference_model text;
begin
  select test_start, test_end, champion_metric, reference_model_id, tie_break_rule
    into setting
  from core.forecast_setting
  where setting_key = 'default' and active = true;
  if not found or setting.test_start is null or setting.test_end is null then raise exception 'TEST_WINDOW_NOT_CONFIGURED'; end if;
  if not exists (select 1 from core.forecast_run where run_id = p_forecast_run_id and status = 'SUCCESS') then raise exception 'FORECAST_RUN_NOT_SUCCESS'; end if;
  reference_model := setting.reference_model_id;

  insert into core.backtest_run(backtest_run_id, forecast_run_id, test_start, test_end, metric, triggered_by)
  values (backtest_key, p_forecast_run_id, setting.test_start, setting.test_end, setting.champion_metric, auth.uid());

  begin
    -- Monthly actuals are sourced exclusively from the validation view.
    with actuals as (
      select item_id, date_trunc('month', usage_date)::date as period, sum(quantity) as actual
      from core.v_test_actual
      where usage_date between setting.test_start and setting.test_end
      group by item_id, date_trunc('month', usage_date)::date
    ), scored as (
      select fr.model_id, fr.model_version, fr.item_id, fr.p50 as forecast, a.actual
      from core.forecast_result fr
      left join actuals a on a.item_id = fr.item_id and a.period = fr.period
      where fr.run_id = p_forecast_run_id and fr.period between date_trunc('month', setting.test_start)::date and date_trunc('month', setting.test_end)::date
    ), metrics as (
      select model_id, max(model_version) as model_version, item_id,
        count(*) filter (where actual is not null and forecast is not null)::integer as n_periods,
        sum(abs(forecast - actual)) filter (where actual is not null and forecast is not null) as abs_error_sum,
        sum(abs(actual)) filter (where actual is not null and forecast is not null) as actual_abs_sum,
        avg(abs(forecast - actual) / nullif(abs(actual), 0)) filter (where actual is not null and forecast is not null and actual <> 0) as mape_avg,
        avg(forecast - actual) filter (where actual is not null and forecast is not null) as bias_value,
        sqrt(avg(power(forecast - actual, 2)) filter (where actual is not null and forecast is not null)) as rmse_value,
        avg(abs(forecast - actual)) filter (where actual is not null and forecast is not null) as mae_value,
        count(*) filter (where actual is null)::integer as missing_actuals,
        count(*) filter (where forecast is null)::integer as missing_forecasts,
        count(*) filter (where actual is not null and forecast is not null and actual <> 0)::integer as mape_periods
      from scored
      group by model_id, item_id
    ), calculated as (
      select m.*, case
        when m.n_periods = 0 then 'NO_COMPARISON_PERIODS'
        when m.missing_actuals > 0 then 'ACTUAL_MISSING'
        when m.missing_forecasts > 0 then 'FORECAST_MISSING'
        when m.actual_abs_sum = 0 then 'ACTUAL_TOTAL_ZERO'
        when m.mape_periods = 0 then 'MAPE_DENOMINATOR_ZERO'
        else null end as reason_code
      from metrics m
    ), ranked as (
      select c.*, case when c.reason_code is null then row_number() over (
        partition by c.item_id
        order by case setting.champion_metric when 'WAPE' then c.abs_error_sum / nullif(c.actual_abs_sum, 0) when 'MAPE' then c.mape_avg when 'RMSE' then c.rmse_value when 'MAE' then c.mae_value end asc nulls last,
                 abs(c.bias_value) asc nulls last, c.rmse_value asc nulls last, c.mae_value asc nulls last, c.model_id
      )::integer end as model_rank
      from calculated c
    )
    insert into core.model_performance(run_id, backtest_run_id, forecast_run_id, model_id, model_version, item_id, n_periods, wape, mape, bias, rmse, mae, rank, calculation_status, reason_code)
    select p_forecast_run_id, backtest_key, p_forecast_run_id, model_id, model_version, item_id, n_periods,
      case when reason_code is null then abs_error_sum / nullif(actual_abs_sum, 0) * 100 end,
      case when reason_code is null then mape_avg * 100 end,
      bias_value, rmse_value, mae_value, model_rank,
      case when reason_code is null then 'SUCCESS' else 'CALCULATION_UNAVAILABLE' end, reason_code
    from ranked;

    update core.model_performance p
       set baseline_improvement = case setting.champion_metric
         when 'WAPE' then case when p.wape is not null and ref.wape is not null and ref.wape <> 0 then (ref.wape - p.wape) / ref.wape * 100 end
         when 'MAPE' then case when p.mape is not null and ref.mape is not null and ref.mape <> 0 then (ref.mape - p.mape) / ref.mape * 100 end
         when 'RMSE' then case when p.rmse is not null and ref.rmse is not null and ref.rmse <> 0 then (ref.rmse - p.rmse) / ref.rmse * 100 end
         when 'MAE' then case when p.mae is not null and ref.mae is not null and ref.mae <> 0 then (ref.mae - p.mae) / ref.mae * 100 end end
      from core.model_performance ref
     where p.backtest_run_id = backtest_key and ref.backtest_run_id = backtest_key and ref.item_id = p.item_id and ref.model_id = reference_model;

    insert into core.champion_model(backtest_run_id, item_id, champion_model_id, model_version, champion_metric, champion_metric_value, wape, mape, bias, rmse, candidate_performance, selection_reason, selection_method, selected_by)
    select backtest_key, best.item_id, best.model_id, best.model_version, setting.champion_metric,
      case setting.champion_metric when 'WAPE' then best.wape when 'MAPE' then best.mape when 'RMSE' then best.rmse when 'MAE' then best.mae end,
      best.wape, best.mape, best.bias, best.rmse,
      candidates.candidate_performance,
      'AUTO: lowest ' || setting.champion_metric || '; tie-break ABS_BIAS, RMSE, MAE, MODEL_ID', 'AUTO', auth.uid()
    from core.model_performance best
    join lateral (select jsonb_agg(jsonb_build_object('model_id', p.model_id, 'model_version', p.model_version, 'WAPE', p.wape, 'MAPE', p.mape, 'Bias', p.bias, 'RMSE', p.rmse, 'MAE', p.mae, 'rank', p.rank, 'reason_code', p.reason_code) order by p.rank nulls last, p.model_id) as candidate_performance from core.model_performance p where p.backtest_run_id = backtest_key and p.item_id = best.item_id) candidates on true
    where best.backtest_run_id = backtest_key and best.rank = 1 and best.calculation_status = 'SUCCESS';

    insert into core.champion_selection_issue(backtest_run_id, item_id, reason_code)
    select backtest_key, p.item_id, 'NO_VALID_MODEL_PERFORMANCE'
    from (select distinct item_id from core.model_performance where backtest_run_id = backtest_key) p
    where not exists (select 1 from core.champion_model c where c.backtest_run_id = backtest_key and c.item_id = p.item_id);

    update core.backtest_run set status = 'SUCCESS', finished_at = now(), message = 'Backtest scoring completed' where backtest_run_id = backtest_key;
  exception when others then
    update core.backtest_run set status = 'FAILED', finished_at = now(), message = sqlerrm where backtest_run_id = backtest_key;
    raise;
  end;
  return backtest_key;
end; $$;

create or replace function core.set_manual_champion(p_backtest_run_id uuid, p_item_id text, p_model_id text, p_reason_text text)
returns bigint language plpgsql security definer set search_path = core, public as $$
declare
  perf core.model_performance%rowtype;
  new_id bigint;
  actor uuid := auth.uid();
begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if p_reason_text is null or length(trim(p_reason_text)) = 0 then raise exception 'MANUAL_CHAMPION_REASON_REQUIRED'; end if;
  select * into perf from core.model_performance where backtest_run_id = p_backtest_run_id and item_id = p_item_id and model_id = p_model_id and calculation_status = 'SUCCESS';
  if not found then raise exception 'CHAMPION_CANDIDATE_NOT_FOUND'; end if;
  insert into core.champion_model(backtest_run_id, item_id, champion_model_id, model_version, champion_metric, champion_metric_value, wape, mape, bias, rmse, candidate_performance, selection_reason, selection_method, selected_by)
  select p_backtest_run_id, p_item_id, p_model_id, perf.model_version, br.metric,
    case br.metric when 'WAPE' then perf.wape when 'MAPE' then perf.mape when 'RMSE' then perf.rmse when 'MAE' then perf.mae end,
    perf.wape, perf.mape, perf.bias, perf.rmse,
    coalesce((select jsonb_agg(jsonb_build_object('model_id', p.model_id, 'model_version', p.model_version, 'WAPE', p.wape, 'MAPE', p.mape, 'Bias', p.bias, 'RMSE', p.rmse, 'MAE', p.mae, 'rank', p.rank, 'reason_code', p.reason_code) order by p.rank nulls last, p.model_id) from core.model_performance p where p.backtest_run_id = p_backtest_run_id and p.item_id = p_item_id), '[]'::jsonb),
    p_reason_text, 'MANUAL', actor
  from core.backtest_run br where br.backtest_run_id = p_backtest_run_id
  returning champion_id into new_id;
  insert into core.audit_log(actor, action, target_type, target_id, before, after)
  values (actor, 'CHAMPION_MANUALLY_SELECTED', 'champion_model', p_item_id, null, jsonb_build_object('backtest_run_id', p_backtest_run_id, 'model_id', p_model_id, 'reason', p_reason_text, 'champion_id', new_id));
  return new_id;
end; $$;

grant execute on function core.run_backtest(uuid), core.set_manual_champion(uuid, text, text, text) to authenticated;

create or replace view analytics.v_backtest_run as select * from core.backtest_run;
create or replace view analytics.v_model_performance as select * from core.model_performance;
create or replace view analytics.v_champion_model as
select distinct on (item_id) * from core.champion_model order by item_id, selected_at desc, champion_id desc;
create or replace view analytics.v_champion_history as select * from core.champion_model;
create or replace view analytics.v_model_comparison as
select p.backtest_run_id, p.forecast_run_id, p.model_id, p.model_version, p.item_id, fr.period,
       fr.p50, fr.p80, fr.p90, fr.sigma, fr.basis, a.actual,
       p.wape, p.mape, p.bias, p.rmse, p.mae, p.baseline_improvement, p.rank, p.calculation_status, p.reason_code,
       (c.champion_model_id = p.model_id and c.backtest_run_id = p.backtest_run_id) as is_champion
from core.model_performance p
join core.forecast_result fr on fr.run_id = p.forecast_run_id and fr.model_id = p.model_id and fr.item_id = p.item_id
left join (select item_id, date_trunc('month', usage_date)::date as period, sum(quantity) as actual from core.v_test_actual group by item_id, date_trunc('month', usage_date)::date) a on a.item_id = fr.item_id and a.period = fr.period
left join (select distinct on (item_id) item_id, backtest_run_id, champion_model_id from core.champion_model order by item_id, selected_at desc, champion_id desc) c on c.item_id = p.item_id;
create or replace view analytics.v_backtest_run_kpi as
select count(*)::integer as total_backtests, count(*) filter (where status = 'SUCCESS')::integer as n_success, count(*) filter (where status = 'FAILED')::integer as n_failed, count(*) filter (where status = 'RUNNING')::integer as n_running from core.backtest_run;

grant select on analytics.v_backtest_run, analytics.v_model_performance, analytics.v_champion_model, analytics.v_champion_history, analytics.v_model_comparison, analytics.v_backtest_run_kpi to authenticated;
